package com.example.ichi.clientcontroller;

import android.os.*;

/**
 * ResultReceiver is used to pass the result from TaskService
 * to the Activity. It is generated by the corresponding
 * activity and let the service return to it.
 *
 * Created by ichiYuan on 4/1/15.
 */
public class MyResultReceiver extends ResultReceiver {

    private Receiver mReceiver;

    public MyResultReceiver(Handler handler) {
        super(handler);
    }

    public void setReceiver(Receiver receiver) {
        mReceiver = receiver;
    }

    public interface Receiver {
        static final int RUNNING = 1;
        static final int FINISHED = 0;
        static final int ERROR = -1;
        public void onReceiveResult(int resultCode, Bundle resultData);
    }

    @Override
    protected void onReceiveResult(int resultCode, Bundle resultData) {
        if (mReceiver != null) {
            mReceiver.onReceiveResult(resultCode, resultData);
        }
    }
}
